type: object
properties:
  version:
    type: integer
    example: 1
  directus:
    type: string
  vendor:
    type: string
  collections:
    type: array
    items:
      $ref: Collections.yaml
  fields:
    type: array
    items:
      $ref: Fields.yaml
  relations:
    type: array
    items:
      $ref: Relations.yaml
